destructors
objectionary/reducing-programs-to-objects pull request #18
Opened 2022-09-08 08:57 UTC by MCJOHN974

#7 @Graur please check

2022-09-08 08:59 UTC, MCJOHN974 commented
I tested it, output is 
```
$ ./run.sh 
AliveDead
```

2022-09-08 11:18 UTC, Graur requested changes

2022-09-08 11:18 UTC, Graur commented on paper.tex
> +  nop > @
@MCJOHN974 I believe we don't need this object here

2022-09-08 11:18 UTC, Graur commented on paper.tex
> +  [] > constructor
@MCJOHN974 Why you change this name from `new` ?

2022-09-08 11:18 UTC, Graur commented on paper.tex
> +[] > app
@MCJOHN974 I believe we don't need to change the code below

2022-09-15 15:41 UTC, MCJOHN974 commented on paper.tex
> +  [] > constructor
@Graur why we should map destructor as ``destructor`` object and construcor as ``new`` object

2026-07-27 17:31 UTC, yegor256 commented
We are closing this pull request, because it has merge conflicts with `master` and has been open for more than a month. Please, forgive us for this: it says nothing about the quality of your work, it's just housekeeping.

If the change still matters to you, please submit a new pull request. It may be very similar to this one, but it has to take into account everything that landed in `master` since then.

Thank you for contributing, and sorry again for the inconvenience!

2026-07-27 17:31 UTC, closed without merging